### ISSUE TITLE
Intel Mac not supported?

### ISSUE THREAD

**Issue by wangpeialex** [Beebeeoii/lominus#20]
**Using a Mac Book Pro 2020 Intel i5**

<img width="918" alt="Screen Shot 2022-01-02 at 15 39 34" src="https://user-images.githubusercontent.com/49505301/147869354-d8ac80bf-4601-4d56-b697-88cde8a3ada5.png">

**Comment by Beebeeoii** [comment]
thanks for raising this... the binary uploaded under releases for macOS was compiled for arm64. I have since compiled for amd64 architecture which should work on Intel Macs.

Do check out [releases](https://github.com/Beebeeoii/lominus/releases/tag/v1.1.2) and try out the amd64 version. You can download it directly here for convenience: [lominus-amd64-unsigned-v1.1.2.dmg](https://github.com/Beebeeoii/lominus/releases/download/v1.1.2/lominus-amd64-unsigned-v1.1.2.dmg)

Hope to hear back from you on whether Lominus works on Intel Macs. Thanks !

**Comment by Beebeeoii** [comment]
Issue should be resolved. Please reopen if issue persists.
