### ISSUE TITLE
Know that the program is currently downloading files

### ISSUE THREAD

**Issue by kevinchua6** [Beebeeoii/lominus#85]
**Is your feature request related to a problem? Please describe.**
When I press sync, I often don't know if it is doing anything. Is it downloading? Has it finished downloading? Often it is hard to tell.

**Describe the solution you'd like**
Having a loading indicator showing what things are in the progress of being downloaded, what things have to be downloaded/have been downloaded etc would be a very nice to have.

**Comment by Beebeeoii** [comment]
Hi ! that's a really good idea. this is just for the case when users manually click 'sync' to sync the files? or do you think users should also be notified upon every cron job fired?

initially, a notification was sent everytime lominus syncs files (both manually and via cron). however, it got to a point when there's just too many notifications and I decided that users might simply be flooded with such notifications and hence i removed that.

but thinking about it again, it might be good to have notifications of the status upon manual syncing as users would like to get some response when they have clicked the sync button. notifications for automatic syncing via cron for status might not be that useful since 1) users wouldnt really know that files are being sync rnrn 2) users are notified at the end of the sync on how many files are downloaded etc

lmk what you think ! thanks a bunch !

ref: [29ebaf4](https://github.com/Beebeeoii/lominus/commit/29ebaf4ba9ae7f44e2a353cf258e5b1a805bf321)

**Comment by kevinchua6** [comment]
Sorry for the late reply! Yes I think it'll be mainly for manual syncing. I think just a single notification after the Cron job has been fired would be fine (if I'm not wrong this is already implemented right)

**Comment by Beebeeoii** [comment]
yup syncs activated by cron fires off a notification

**Comment by Beebeeoii** [comment]
issue addressed with #97
